export default [
  {
    id: 30,
    link: 'KeTWBgBylrs',
    lable: 'Benny Benassi - Whos Your Daddy?',
    lableSecondary: 'Whos Your Daddy?',
  },
  {
    id: 0,
    link: 'ZzHUzctT4bo',
    lable: 'Крестная Семья',
    lableSecondary: 'Хей Герла',
  },
  {
    id: 1,
    link: 'WWPpLDdSTME',
    lable: 'Крестная Семья',
    lableSecondary: 'Мусор на бабки',
  },
  {
    id: 2,
    link: 'Ead0vHhVyzI',
    lable: 'Крестная Семья',
    lableSecondary: 'Гос Дума',
  },
  {
    id: 3,
    link: 'BXnqsPcMyGk',
    lable: 'Крестная Семья',
    lableSecondary: 'Кто не пьёт тот не бёот',
  },
  {
    id: 4,
    link: 'OwdlqquJDK4',
    lable: 'King of my Castel',
    lableSecondary: '1999',
  },
  {
    id: 5,
    link: 'nWAGLkyxQG0',
    lable: 'With Kallyfa',
    lableSecondary: 'Black and Yellow',
  },
  {
    id: 6,
    link: 'T_tAtLAdV10',
    lable: '6',
    lableSecondary: '6',
  },
  {
    id: 7,
    link: '8CdcCD5V-d8',
    lable: '7 Семья',
    lableSecondary: '7 на бабки',
  },
  {
    id: 8,
    link: 'TOrnUquxtwA',
    lable: '8 Семья',
    lableSecondary: '8 Дума',
  },
  {
    id: 9,
    link: 'mMfxI3r_LyA',
    lable: '9 Семья',
    lableSecondary: '9',
  },
  {
    id: 10,
    link: 'bfcQg-befiw',
    lable: '10',
    lableSecondary: '10-befiw',
  },
  {
    id: 11,
    link: 'h3YVKTxTOgU',
    lable: '10',
    lableSecondary: '10 and Yellow',
  },
  {
    id: 12,
    link: 'DyDfgMOUjCI',
    lable: '12 Семья',
    lableSecondary: '12 Герла',
  },
  {
    id: 13,
    link: 'WWPpLDdSTME',
    lable: '13 Семья',
    lableSecondary: '13 на бабки',
  },
  {
    id: 14,
    link: 'yyDUC1LUXSU',
    lable: '14 Семья',
    lableSecondary: '14 Дума',
  },
  {
    id: 15,
    link: 'IVUTMGbitsE',
    lable: '15 Семья',
    lableSecondary: '15 не пьёт тот не бёот',
  },
  {
    id: 16,
    link: 'UXWFqxKU2qA',
    lable: '16 of my Castel',
    lableSecondary: '16',
  },
  {
    id: 17,
    link: 'GFOtRrFH3z0',
    lable: '17 Kallyfa',
    lableSecondary: '17 and Yellow',
  },
  {
    id: 18,
    link: 'bQLi3GTJAug',
    lable: '18',
    lableSecondary: '18',
  },
  {
    id: 19,
    link: 'oNTEsdd1U6w',
    lable: '19 Семья',
    lableSecondary: '19 на бабки',
  },
  {
    id: 20,
    link: 'jZSPAp8kCl4',
    lable: '20 Семья',
    lableSecondary: '20 Дума',
  },
  {
    id: 21,
    link: '4qlCC1GOwFw',
    lable: '21 Семья',
    lableSecondary: '9',
  },
  {
    id: 22,
    link: 'RQ9_TKayu9s',
    lable: '22',
    lableSecondary: '22-befiw',
  },
  {
    id: 23,
    link: 'uelHwf8o7_U',
    lable: '23',
    lableSecondary: '23 and Yellow',
  },
  {
    id: 24,
    link: 'EHkozMIXZ8w',
    lable: '24 Семья',
    lableSecondary: '19 на бабки',
  },
  {
    id: 25,
    link: '5RDSkR8_AQ0',
    lable: '25 Семья',
    lableSecondary: '25 Дума',
  },
  {
    id: 26,
    link: 'um4-d7VzZiE',
    lable: '26 Семья',
    lableSecondary: '26',
  },
  {
    id: 27,
    link: '4iQZ9HS0L18',
    lable: '27',
    lableSecondary: '27-befiw',
  },
  {
    id: 28,
    link: 'eWViUNBV-dw',
    lable: '28',
    lableSecondary: '28 and Yellow',
  },
  {
    id: 29,
    link: '4jgfyJcqpSo',
    lable: '29',
    lableSecondary: '29 and Yellow',
  },
];
